version: '2'
services:

  loans-app:
    image: sumitg/loans-app
    ports:
    - "8080:8080"

  ldap:
    image: sumitg/knox-mten
    command: /ldap.sh

  knox:
    image: sumitg/knox-mten
    ports:
    - "8443:8443"
    command: /gateway.sh
    volumes:
     - ./logs:/knox/logs
    depends_on:
    - ldap

